version: "3.9"

services:
  auth-db:
    restart: always
    ports: !reset [] # 🔒 Menghapus ekspos port 5434 ke luar
    environment:
      POSTGRES_USER: prod_user_secure
      POSTGRES_PASSWORD: prod_password_super_secret

  item-db:
    restart: always
    ports: !reset [] # 🔒 Menghapus ekspos port 5433 ke luar
    environment:
      POSTGRES_USER: prod_user_secure
      POSTGRES_PASSWORD: prod_password_super_secret

  auth-service:
    restart: always
    ports: !reset [] # 🔒 Menghapus ekspos port 8001 ke luar
    environment:
      - ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgresql://prod_user_secure:prod_password_super_secret@auth-db:5432/bye_virus

  item-service:
    restart: always
    ports: !reset [] # 🔒 Menghapus ekspos port 8002 ke luar
    environment:
      - ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgresql://prod_user_secure:prod_password_super_secret@item-db:5432/bye_virus

  frontend:
    restart: always
    ports: !reset [] # 🔒 Menghapus ekspos port 3000 ke luar
    environment:
      - NODE_ENV=production

  gateway:
    restart: always
    ports:
      - "80:80" # 🚪 HANYA pintu ini yang boleh diakses publik dari luar server!